---
title: "task_01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("here")
```

```{r}
library(tidyverse)
library(janitor)
library(here)
```

#Loaded in the dataframe "decathlon.rds" for cleaning

#Turns out i want better column names, so i've changed them.


```{r}
decathlon <- 
  decathlon %>%
  clean_names()
decathlon


```
#designated the athlete names as a new column

```{r}
decath <- rownames_to_column(decathlon, "athlete_name")
decath
```
#I need the athletes names all in either upper or lower so they act the same if i'm looking across both competitions. 

```{r}
decath <- decath %>% 
  mutate(athlete_name = str_to_lower(athlete_name))

decath
```
#First i've pivoted the table longer to have fewer columns and make the data more manageable. 

```{r}
decath_long <- decath %>%
  pivot_longer(cols = ("x100m":"x1500m"), 
               names_to = "event", 
               values_to = "result")
decath_long
```

```{r}
write_csv(decath_long, "/Users/user/dirty_data_project/Task1/Clean_data/clean_data.csv")
```

